name: Packages

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  windows:
    name: Windows

    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64]

    runs-on: windows-latest

    env:
      BITS: '${{ matrix.bits }}'
      #ICINGA_BUILD_PROJECT: icinga2
      ICINGA_BUILD_TYPE: snapshot
      UPSTREAM_GIT_URL: file://D:/a/icinga2/icinga2/.git
      #VS_INSTALL_PATH: >-
      #  C:\Program Files (x86)\Microsoft Visual Studio\2019
      #VS150COMNTOOLS: >-
      #  /c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools

    steps:
      - name: Build tools
        run: |
          choco install -y visualstudio2019community
          choco install -y visualstudio2019-workload-netcoretools
          choco install -y visualstudio2019-workload-vctools
          choco install -y visualstudio2019-workload-manageddesktop
          choco install -y visualstudio2019-workload-nativedesktop
          choco install -y visualstudio2019-workload-universal
          choco install -y visualstudio2019buildtools
          choco install -y cmake
          choco install -y winflexbison3
          choco install -y windows-sdk-8.1
          choco install -y wixtoolset

      - name: Checkout HEAD
        uses: actions/checkout@v1

      - name: windows-icinga2
        run: |
          git clone https://git.icinga.com/packaging/windows-icinga2.git

      - name: Source
        run: |
          git checkout -B master
          cd windows-icinga2
          & .\source.ps1

      - name: Binary
        working-directory: windows-icinga2
        run: |
          & .\build.ps1
